version: '3'

services: 
  redis:
      image: redis:alpine
      container_name: redis
      restart: unless-stopped
      deploy:
        resources:
          limits:
            memory: 2048M
      command: redis-server /etc/redis/redis.conf
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/data
        - ./redis.conf:/etc/redis/redis.conf
      networks:
        - redis


volumes:
  redis-data:
    driver: local
    name: redis-data

networks:
  redis: 
    external: true